version: '3.8'

services:
  percona:
    image: percona:latest
    container_name: percona_db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - percona_data:/var/lib/mysql
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    platform: linux/amd64
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  percona_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
